### PR TITLE
Remove the device reset, it's causing big performace problems

### PR DESCRIPTION
**Pull request by qpernil**
The status page takes over a minute in a Ubuntu Groovy VM on VMWare ESXi 7.0. With this change 45ms. I don't see any problems with disconnected/reconnected devices.

### CODE REVIEW

**Comment by qpernil** [comment]
python-yubihsm tests pass with this change

**Comment by qpernil** [comment]
Just a note - This causes performance degradation on a physical Groovy ubuntu machine as well, just not as severe. The diff is 276ms to handle /status on master, and 2ms on the no-reset-device branch

**Comment by joernheissler** [comment]
I'm using my YubiHSM through an SEH UTN dongleserver (https://www.seh-technology.com/de/produkte/dongleserver.html); a virtual machine (linux inside vmware) is running yubihsm-connector.
It did not work without this patch, broke badly on device reset.
With the patch it appears to works.

(only tested once with each version).

Thanks and merry xmas!

**Review by syntaxcase — COMMENTED** [review]
Nice work! The only thing that needs to be addressed before this is merged is that the `go.sum` file shouldn't be deleted, just eventually updated with the new version of the dependencies (since the `gousb` version was updated).

**Review by syntaxcase — APPROVED** [review]

**Pull request merged**
