### PR TITLE
Switch to github.com/google/gousb

### LINKED ISSUE #3: go-libusb is deprecated and archived
The go-libusb library [1] used in yubihsm-connector is deprecated (and archived fork of [2]).

From packaging and security point of view, it is not a good idea to package archived fork of deprecated library.

Would it be possible to use the original version or "migrate" to the new gousb [3] that is alive and kicking?

I am not a go developer so I do not know what would it take to do so.

[1] https://github.com/thorduri/go-libusb
[2] https://github.com/kylelemons/gousb
[3] https://github.com/google/gousb

### PR DESCRIPTION
**Pull request by QuLogic**
As noted in #3, there are still two issues:

1.    the ZLP is not sent anymore, you can test that with yubihsm-shell by executing `plain echo 3 61`. I did some digging and it's gousb that doesn't allow sending an empty buffer.
1.    Errors out when resetting a device. If you run the tests in pytnon-yubihsm it will fail when the tests reset the device (don't run these tests on a production device!).

But as I don't own any devices, I really have no idea how to fix these. Any ideas would be welcome.

Fixes #3.

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm able to run both python-yubihsm and yubihsm-shell tests without issue now, though I can't seem to get yubihsm-shell to work from the command-line itself (which confuses me since its tests work.)

**Comment by syntaxcase** [comment]
Hi, nice work. It looks good to me and I want to merge it, just going through some more tests. Is this code contributed under this repository license (Apache 2.0)?

**Comment by QuLogic** [comment]
Yes.

**Comment by syntaxcase** [comment]
Merged, thanks for your contribution!

**Pull request merged**
